Repository openshift/openshift-apiserver, pull requests merged in 2019-10, with the labels that each got.

#29 Bug 1755115: allow scheduled imagestream imports for dockerimages with sha/digest …
  pkg/image/apis/image/validation/validation.go
  pkg/image/apis/image/validation/validation_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#33 Update OWNERS
  pkg/api/OWNERS
  pkg/authorization/OWNERS
  pkg/oauth/OWNERS
  pkg/project/OWNERS
  pkg/security/OWNERS
  pkg/user/OWNERS
Labels: approved, lgtm, size/S

#31 udpate make images target
  Makefile
Labels: approved, lgtm, size/XS

#38 project/auth/cache: add more context to errors
  pkg/project/auth/cache.go
Labels: approved, lgtm, size/XS

#39 updates k8s.io/apiserver to point to openshift-apiserver-4.3-kubernetes-1.16.2 branch
  go.mod
  go.sum
  vendor/github.com/certifi/gocertifi/gen.go
  vendor/github.com/docker/docker/pkg/archive/example_changes.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/config_selfclient.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/storage/value/transformer.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
