Repository openshift/openshift-apiserver, pull requests merged in 2019-11, with the labels that each got.

#42 Add capability of reading configmaps to shared-resource-viewer role
  pkg/bootstrappolicy/namespace_policy.go
  test/testdata/bootstrappolicy/bootstrap_namespace_roles.yaml
Labels: approved, lgtm, size/S

#43 metrics: fix registration and name of version metric
  pkg/version/version.go
Labels: approved, lgtm, size/XS

#45 vendor: pin etcd v3.3.17 and bbolt v1.3.3
  go.mod
  go.sum
  vendor/github.com/coreos/bbolt/bolt_riscv64.go
  vendor/github.com/coreos/bbolt/db.go
  vendor/github.com/coreos/bbolt/freelist.go
  vendor/github.com/coreos/bbolt/tx.go
  vendor/github.com/coreos/etcd/clientv3/balancer/resolver/endpoint/endpoint.go
  vendor/github.com/coreos/etcd/clientv3/client.go
  vendor/github.com/coreos/etcd/clientv3/credentials/credentials.go
  vendor/github.com/coreos/etcd/embed/config.go
  vendor/github.com/coreos/etcd/etcdserver/api/v2http/client.go
  vendor/github.com/coreos/etcd/mvcc/backend/backend.go
  vendor/github.com/coreos/etcd/mvcc/kvstore.go
  vendor/github.com/coreos/etcd/mvcc/metrics.go
  vendor/github.com/coreos/etcd/pkg/testutil/leak.go
  vendor/github.com/coreos/etcd/pkg/transport/listener.go
  vendor/github.com/coreos/etcd/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#47 remove side-channel wiring for cluster authentication
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
Labels: approved, lgtm, size/S

#48 Bug 1757553: bump apiserver-lib-go for escalating externalIPs
  go.mod
  go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/authorization/scope/converter.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#49 Allow new images from a referenced repository
  pkg/image/apis/image/validation/fake/fake.go
  pkg/image/apis/image/validation/validation.go
  pkg/image/apis/image/validation/validation_test.go
  pkg/image/apis/image/validation/whitelist/whitelister.go
  pkg/image/apis/image/validation/whitelist/whitelister_test.go
Labels: approved, lgtm, size/L
