Repository openshift/openshift-apiserver, pull requests merged in 2019-07, with the labels that each got.

#2 images: fix the path from which the binary is being built
  Dockerfile
  Dockerfile.rhel
Labels: lgtm, size/S

#3 Fix vendor
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/oc/main.go
  vendor/github.com/openshift/library-go/alpha-build-machinery/make/examples/multiple-binaries/cmd/openshift/main.go
  vendor/k8s.io/kubernetes/third_party/etcd.BUILD
Labels: approved, lgtm, size/M

#4 move Dockerfiles to images/ to comply to ART reqs
  Makefile
  images/Dockerfile
  images/Dockerfile.rhel
Labels: approved, lgtm, size/XS
