Repository openshift/openshift-apiserver, pull requests merged in 2020-05, with the labels that each got.

#97 Bug 1830887: fix projectrequestlimit conversion
  hack/update-generated-conversions.sh
  pkg/project/apiserver/admission/apis/requestlimit/v1/doc.go
  pkg/project/apiserver/admission/apis/requestlimit/v1/register.go
  pkg/project/apiserver/admission/apis/requestlimit/v1/zz_generated.conversion.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#98 Bug 1830887: fix test scheme for templates
  pkg/template/apiserver/registry/template/rest_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#96 Bug 1830887: fix the rollback generator scheme usage
  pkg/apps/apiserver/registry/rollback/rollback_generator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#99 Bug 1826523: Bump openshift/api to 0422dc17083e9e8df18d029f3f34322e96e9c326
  go.mod
  go.sum
  hack/openapi-violation.list
  pkg/openapi/zz_generated.openapi.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#107 Bug 1795163: openshift-apiserver operator not available when used for single node cluster (CRC)
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication_dynamic_request_header.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#102 Bug 1731222: unwarranted SARs on foreground GC of objects with owner refs
  pkg/build/apiserver/admission/strategyrestrictions/admission.go
  pkg/build/apiserver/admission/strategyrestrictions/helpers.go
  pkg/build/apiserver/admission/strategyrestrictions/helpers_test.go
  pkg/template/apiserver/registry/templateinstance/helpers.go
  pkg/template/apiserver/registry/templateinstance/helpers_test.go
  pkg/template/apiserver/registry/templateinstance/strategy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#109 Bug 1821500: bump to kube 1.17.4
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/cryptobyte/string.go
  vendor/golang.org/x/crypto/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/poly1305/poly1305.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_arm.go
  vendor/golang.org/x/crypto/poly1305/sum_arm.s
  vendor/golang.org/x/crypto/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
