Repository openshift/openshift-apiserver, pull requests merged in 2020-07, with the labels that each got.

#116 Bug 1844479: Add custom conversion for binary builds
  pkg/api/serialization_test.go
  pkg/build/apis/build/v1/conversion.go
  pkg/build/apis/build/v1/conversion_test.go
  pkg/build/apis/build/v1/register.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#115 Bug 1751258: Using manifest digest on manifest list import
  pkg/image/apiserver/importer/importer.go
  pkg/image/apiserver/importer/importer_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#124 Add image registry team to pkg/image OWNERS
  pkg/image/OWNERS
Labels: approved, lgtm

#125 Update system:router cluster role for endpointslices
  pkg/bootstrappolicy/policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, lgtm

#121 IR-99: Adding metric for registry v1 protocol imports
  pkg/image/apiserver/importer/importer.go
  pkg/image/apiserver/importer/metrics.go
Labels: approved, lgtm
