Repository openshift/openshift-apiserver, pull requests merged in 2020-01, with the labels that each got.

#65 Use IPv6 in resolver cache tests
  pkg/image/apiserver/registryhostname/environmentresolvercache_test.go
Labels: approved, lgtm, size/XS

#52 add conditions to build api
  pkg/build/apis/build/types.go
  pkg/build/apis/build/v1/zz_generated.conversion.go
  pkg/build/apis/build/zz_generated.deepcopy.go
  pkg/build/apiserver/buildgenerator/generator.go
  pkg/build/apiserver/registry/build/strategy.go
  pkg/build/apiserver/registry/build/strategy_test.go
Labels: approved, lgtm, size/XL

#51 Add the imagetags resource to v1
  pkg/bootstrappolicy/namespace_policy.go
  pkg/bootstrappolicy/policy.go
  pkg/image/apis/image/register.go
  pkg/image/apis/image/types.go
  pkg/image/apis/image/v1/zz_generated.conversion.go
  pkg/image/apis/image/validation/validation.go
  pkg/image/apis/image/validation/validation_test.go
  pkg/image/apis/image/zz_generated.deepcopy.go
  pkg/image/apiserver/apiserver.go
  pkg/image/apiserver/registry/imagetag/rest.go
  pkg/image/apiserver/registry/imagetag/rest_test.go
  pkg/image/apiserver/registry/imagetag/strategy.go
  pkg/image/printers/internalversion/printer.go
  pkg/image/printers/internalversion/printer_test.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
  test/testdata/bootstrappolicy/bootstrap_namespace_roles.yaml
Labels: approved, lgtm, size/XXL

#70 Bug 1795705: increase error logging around apiserver binary build flow
  pkg/build/apiserver/buildgenerator/generator.go
  pkg/build/apiserver/registry/buildconfiginstantiate/rest.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#71 Bug 1795705: return actual instantiate error for binary builds
  pkg/build/apiserver/registry/buildconfiginstantiate/rest.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#69 Bug 1788700: include ISI error message changes when determining new generation need
  pkg/image/apiserver/registry/imagestreamimport/rest.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
