Repository openshift/openshift-apiserver, pull requests merged in 2020-04, with the labels that each got.

#86 Bug 1813964: fixes configmap "extension-apiserver-authentication" not found
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/static_content.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#87 Bug 1814207: fixes configmap "extension-apiserver-authentication" not found
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/static_content.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#83 Bug 1816534: DEVEXP-424: Leveraging node credentials during image stream import
  go.mod
  pkg/image/apiserver/importer/credentials.go
  pkg/image/apiserver/importer/credentials_test.go
  pkg/image/apiserver/importer/import_integration_test.go
  pkg/image/apiserver/importer/importer.go
  pkg/image/apiserver/importer/importer_test.go
  pkg/image/apiserver/importer/staticcredentials.go
  pkg/image/apiserver/registry/imagestreamimport/rest.go
  vendor/github.com/docker/docker/pkg/stringid/README.md
  vendor/github.com/docker/docker/pkg/stringid/stringid.go
  vendor/github.com/docker/docker/pkg/tarsum/builder_context.go
  vendor/github.com/docker/docker/pkg/tarsum/fileinfosums.go
  vendor/github.com/docker/docker/pkg/tarsum/tarsum.go
  vendor/github.com/docker/docker/pkg/tarsum/tarsum_spec.md
  vendor/github.com/docker/docker/pkg/tarsum/versioning.go
  vendor/github.com/docker/docker/pkg/tarsum/writercloser.go
  vendor/github.com/docker/docker/registry/auth.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/config_unix.go
  vendor/github.com/docker/docker/registry/config_windows.go
  vendor/github.com/docker/docker/registry/endpoint_v1.go
  vendor/github.com/docker/docker/registry/errors.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/github.com/docker/docker/registry/resumable/resumablerequestreader.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/service_v1.go
  vendor/github.com/docker/docker/registry/service_v2.go
  vendor/github.com/docker/docker/registry/session.go
  vendor/github.com/docker/docker/registry/types.go
  vendor/github.com/docker/go-connections/sockets/README.md
  vendor/github.com/docker/go-connections/sockets/inmem_socket.go
  vendor/github.com/docker/go-connections/sockets/proxy.go
  vendor/github.com/docker/go-connections/sockets/sockets.go
  vendor/github.com/docker/go-connections/sockets/sockets_unix.go
  vendor/github.com/docker/go-connections/sockets/sockets_windows.go
  vendor/github.com/docker/go-connections/sockets/tcp_socket.go
  vendor/github.com/docker/go-connections/sockets/unix_socket.go
  vendor/github.com/docker/go-connections/tlsconfig/certpool_go17.go
  vendor/github.com/docker/go-connections/tlsconfig/certpool_other.go
  vendor/github.com/docker/go-connections/tlsconfig/config.go
  vendor/github.com/docker/go-connections/tlsconfig/config_client_ciphers.go
  vendor/github.com/docker/go-connections/tlsconfig/config_legacy_client_ciphers.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#90 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#93 Buildconfig: Check emptyness of buildRequest.TriggedBy via len
  pkg/build/apiserver/registry/buildconfiginstantiate/rest.go
Labels: approved, lgtm

#92 [release 4-3] Bug 1824127: fixes configmap "extension-apiserver-authentication" not found
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go
  vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/static_content.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#88 Remove system:registry cluster role
  pkg/bootstrappolicy/constants.go
  pkg/bootstrappolicy/policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, lgtm
