Repository openshift/openshift-apiserver, pull requests merged in 2020-06, with the labels that each got.

#100 [release-4.4] Bug 1829327: allow patch for updating namespace
  pkg/bootstrappolicy/controller_policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#104 Bug 1832762: updates Dockerfile.rhel to golang 1.13 and ocp:4.4
  Makefile
  images/Dockerfile
  images/Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#114 Bug 1843496: project: improve error message on cluster-scoped template objects
  pkg/project/apiserver/registry/projectrequest/delegated/delegated.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#103 Bug 1840857: openshift-apiserver doesn't live reload extension-apiserver-authentication trust
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication_dynamic_request_header.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#113 Bug 1841035: Modify basic-user and storage-admin to be aggregated
  pkg/bootstrappolicy/all_test.go
  pkg/bootstrappolicy/constants.go
  pkg/bootstrappolicy/policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#117 Bug 1844485: fix apps conversions
  pkg/apps/apis/apps/v1/conversion.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#110 Bug 1774616: Remove insecureSkipTLSVerifyBackend bypass for BuildLogOptions
  go.mod
  go.sum
  pkg/build/apis/build/internal_helpers/internal_helpers.go
  pkg/build/apis/build/log_options_test.go
  pkg/build/apis/build/types.go
  pkg/build/apis/build/v1/zz_generated.conversion.go
  pkg/openapi/zz_generated.openapi.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#101 [release-4.3] Bug 1829328: allow patch for updating namespace
  pkg/bootstrappolicy/controller_policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
