Repository openshift/openshift-apiserver, pull requests merged in 2020-03, with the labels that each got.

#79 Remove the namespace security allocation controller role
  pkg/bootstrappolicy/controller_policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, lgtm, size/M

#80 [release 4.5] Bug 1811801: /readyz should start returning failure on shutdown initiation
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#81 [release 4.4] Bug 1811202: /readyz should start returning failure on shutdown initiation
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M
