Repository openshift/openshift-apiserver, pull requests merged in 2020-09, with the labels that each got.

#133 Bug 1844471: updates the Dockerfile to use golang 1.14
  images/Dockerfile
  images/Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#135 Bug 1877363: fix missing conversions for DeploymentLogOptions
  pkg/apps/apis/apps/v1/conversion.go
  pkg/apps/apis/apps/v1/register.go
  pkg/apps/apis/apps/v1/zz_generated.conversion.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#129 Bug 1820075: Delete policy for ingress-to-route-controller
  pkg/bootstrappolicy/controller_policy.go
  pkg/bootstrappolicy/dead.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#143 Bug 1862532: Fix label value validation for BuildConfigs
  pkg/build/apiserver/buildgenerator/generator.go
  pkg/build/apiserver/buildgenerator/generator_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
