Repository openshift/openshift-apiserver, pull requests merged in 2021-07, with the labels that each got.

#222 Bug 1974651: Remove client for Docker v1 API
  pkg/image/apiserver/apiserver.go
  pkg/image/apiserver/importer/dockerv1client/client.go
  pkg/image/apiserver/importer/dockerv1client/client_test.go
  pkg/image/apiserver/importer/dockerv1client/dockerregistryclient_test.go
  pkg/image/apiserver/importer/image.go
  pkg/image/apiserver/importer/import_integration_test.go
  pkg/image/apiserver/importer/importer.go
  pkg/image/apiserver/importer/importer_test.go
  pkg/image/apiserver/importer/metrics.go
  pkg/image/apiserver/registry/imagestreamimport/rest.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#229 Remove Dockerhub image test
  pkg/image/apiserver/importer/import_integration_test.go
Labels: approved, lgtm

#230 Bug 1978627: Validate secret name and configMap name
  .gitignore
  pkg/build/apis/build/validation/validation.go
  pkg/build/apis/build/validation/validation_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#231 Provide plugins access to openshift informers
  pkg/cmd/openshift-apiserver/openshiftadmission/openshift_informers_initializer.go
  pkg/cmd/openshift-apiserver/openshiftadmission/plugin_initializer.go
  pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/build.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/console.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/network.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/project.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/build.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/console.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/image.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/network.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/project.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/scheduler.go
  vendor/modules.txt
Labels: approved, lgtm

#232 expose config and route informers on informeraccess interface
  pkg/cmd/openshift-apiserver/openshiftadmission/plugin_initializer.go
Labels: approved, lgtm

#234 remove openshift initializer pkgs out of pkg/cmd
  pkg/admission/initializer.go
  pkg/admission/interfaces.go
  pkg/cmd/openshift-apiserver/openshiftadmission/openshift_informers_initializer.go
  pkg/cmd/openshift-apiserver/openshiftadmission/plugin_initializer.go
Labels: approved, lgtm

#238 Bug 1971332: revert incorrect ssh scp fix
  pkg/build/apis/build/validation/s2i_validation.go
  pkg/build/apis/build/validation/validation_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
