Repository openshift/openshift-apiserver, pull requests merged in 2021-04, with the labels that each got.

#198 sets shutdown-delay-duration from OpenShiftAPIServerConfig
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
Labels: approved, lgtm

#195 bump apiserver-lib-go for looser username validation
  go.mod
  go.sum
  vendor/github.com/openshift/apiserver-library-go/pkg/admission/imagepolicy/imagereferencemutators/pods.go
  vendor/github.com/openshift/apiserver-library-go/pkg/apivalidation/uservalidation.go
  vendor/modules.txt
Labels: approved, lgtm

#188 Bug 1931404: fixes a data race in SerializeObject function
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#203 Bug 1953563: Add .ci-operator.yaml with build_root_image
  .ci-operator.yaml
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
