Repository openshift/openshift-apiserver, pull requests merged in 2021-01, with the labels that each got.

#174 Bug 1910257: bump(golang.org/x/crypto)
  go.mod
  go.sum
  vendor/golang.org/x/crypto/internal/subtle/aliasing.go
  vendor/golang.org/x/crypto/internal/subtle/aliasing_purego.go
  vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/salsa20/salsa/salsa20_amd64.go
  vendor/golang.org/x/crypto/salsa20/salsa/salsa20_amd64.s
  vendor/golang.org/x/crypto/salsa20/salsa/salsa20_noasm.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#177 Bug 1915661: update image-pruner role to include jobs, cronjobs and statefulsets
  pkg/bootstrappolicy/policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#161 Bug 1894916: Panic output due to timeouts in openshift-apiserver
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/apiserver/pkg/server/filters/wrap.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authorization.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
