Repository openshift/openshift-apiserver, pull requests merged in 2021-03, with the labels that each got.

#190 Bug 1933599: bump k8s.io/apiserver to 1.20.4
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go
  vendor/k8s.io/apiserver/pkg/quota/v1/resources.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authorization.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/OWNERS
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#185 Bug 1895053: Propagate new MountTrustedCA field
  go.mod
  go.sum
  pkg/build/apis/build/types.go
  pkg/build/apis/build/v1/zz_generated.conversion.go
  pkg/build/apis/build/zz_generated.deepcopy.go
  pkg/build/apiserver/buildgenerator/generator.go
  pkg/build/apiserver/buildgenerator/generator_test.go
  pkg/openapi/zz_generated.openapi.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#192 limit basic-user cluster role well-known access to oauth-authorization-server only
  pkg/bootstrappolicy/policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, lgtm

#187 Bug 1917904: bump k8s.io/apiserver to 1.20.4
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go
  vendor/k8s.io/apiserver/pkg/quota/v1/resources.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authorization.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/OWNERS
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
