Repository openshift/openshift-apiserver, pull requests merged in 2021-02, with the labels that each got.

#180 Bug 1900989: policy/unidling-controller: allow get/update on services
  pkg/bootstrappolicy/controller_policy.go
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#167 Bug 1896977: Enhance API host name validation
  go.mod
  go.sum
  hack/openapi-violation.list
  pkg/openapi/zz_generated.openapi.go
  pkg/route/apis/route/validation/validation.go
  pkg/route/apis/route/validation/validation_test.go
  pkg/route/apiserver/registry/route/etcd/etcd_test.go
  pkg/route/apiserver/registry/route/strategy_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/library-go/pkg/route/routeapihelpers/routeapihelpers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#181 Bug 1912590: Populate publicDockerImageRepository for new image streams
  pkg/image/apiserver/registry/imagestream/strategy.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#182 Bug 1919966: fixes a data race in SerializeObject function
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#164 Bug 1905991: Detecting broken connections to the Kube API takes up to 15 minutes
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/timeout.go
  vendor/k8s.io/apiserver/pkg/server/filters/wrap.go
  vendor/k8s.io/apiserver/pkg/server/genericapiserver.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/server/options/authorization.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
