Repository openshift/openshift-apiserver, pull requests merged in 2022-01, with the labels that each got.

#264 Bug 2037075: Add CSI VolumeSource to build types
  go.mod
  go.sum
  pkg/build/apis/build/types.go
  pkg/build/apis/build/v1/zz_generated.conversion.go
  pkg/build/apis/build/validation/validation.go
  pkg/build/apis/build/validation/validation_test.go
  pkg/build/apis/build/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml-patch
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01_imagepruner.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#268 Bug 2032589: Make OriginImageMutators aware of origin objects
  pkg/image/apiserver/admission/imagepolicy/originimagereferencemutators/meta.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, qe-approved

#267 projects: add rw mutex to auth cache
  pkg/project/auth/cache.go
  pkg/project/auth/cache_test.go
Labels: lgtm, approved

#272 Bug 2047335: fix panic from printer
  pkg/project/printers/internalversion/printer.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
