Repository openshift/openshift-apiserver, pull requests merged in 2022-10, with the labels that each got.

#319 Remove k8s.io/kubernetes deps from route validation/defaulting.
  pkg/route/apis/route/validation/validation.go
  pkg/route/apiserver/admission/routehostassignment/assignment.go
Labels: lgtm, approved

#322 Drop AllocateRouterShard from hostname allocation interface.
  pkg/route/apiserver/admission/routehostassignment/assignment.go
  pkg/route/apiserver/admission/routehostassignment/assignment_test.go
  pkg/route/apiserver/registry/route/etcd/etcd.go
  pkg/route/apiserver/registry/route/etcd/etcd_test.go
  pkg/route/apiserver/registry/route/strategy.go
  pkg/route/apiserver/registry/route/strategy_test.go
  pkg/route/apiserver/routeinterfaces/interfaces.go
  pkg/route/apiserver/simplerouteallocation/plugin.go
  pkg/route/apiserver/simplerouteallocation/plugin_test.go
Labels: lgtm, approved

#321 Perform route host defaulting and update authz using v1 types.
  pkg/route/apiserver/admission/routehostassignment/adapter.go
  pkg/route/apiserver/admission/routehostassignment/assignment.go
  pkg/route/apiserver/admission/routehostassignment/assignment_test.go
  pkg/route/apiserver/registry/route/etcd/etcd.go
  pkg/route/apiserver/registry/route/etcd/etcd_test.go
  pkg/route/apiserver/registry/route/strategy.go
  pkg/route/apiserver/registry/route/strategy_test.go
  pkg/route/apiserver/simplerouteallocation/plugin.go
  pkg/route/apiserver/simplerouteallocation/plugin_test.go
Labels: lgtm, approved

#326 OCPBUGS-2803: Revert "projects: add rw mutex to auth cache"
  pkg/project/auth/cache.go
  pkg/project/auth/cache_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#290 IR-258: ImageStreamImport manifest list support
  pkg/api/serialization_test.go
  pkg/image/apis/image/types.go
  pkg/image/apis/image/v1/conversion.go
  pkg/image/apis/image/v1/defaults.go
  pkg/image/apis/image/v1/zz_generated.conversion.go
  pkg/image/apis/image/v1/zz_generated.defaults.go
  pkg/image/apis/image/validation/validation.go
  pkg/image/apis/image/validation/validation_test.go
  pkg/image/apis/image/zz_generated.deepcopy.go
  pkg/image/apiserver/importer/image.go
  pkg/image/apiserver/importer/image_test.go
  pkg/image/apiserver/importer/importer.go
  pkg/image/apiserver/importer/importer_manifestlist_test.go
  pkg/image/apiserver/importer/importer_test.go
  pkg/image/apiserver/importer/test/image-secrets.json
  pkg/image/apiserver/importer/testdata/config-linux-amd64.json
  pkg/image/apiserver/importer/testdata/config-linux-arm64.json
  pkg/image/apiserver/importer/testdata/manifest-linux-amd64.json
  pkg/image/apiserver/importer/testdata/manifest-linux-arm64.json
  pkg/image/apiserver/importer/testdata/manifest-list.json
  pkg/image/apiserver/registry/imagestreamimport/imagecreater.go
  pkg/image/apiserver/registry/imagestreamimport/rest.go
  pkg/image/apiserver/registry/imagestreamimport/rest_test.go
  pkg/image/apiserver/registry/imagestreamtag/rest_test.go
  pkg/image/apiserver/registry/imagetag/rest_test.go
Labels: lgtm, approved, qe-approved

#325 IR-259: changing image stream importMode increments its generation
  pkg/image/apiserver/registry/imagestream/strategy.go
Labels: lgtm, approved, qe-approved

#327 [release-4.11] OCPBUGS-2809: Revert "projects: add rw mutex to auth cache"
  pkg/project/auth/cache.go
  pkg/project/auth/cache_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
