Repository openshift/openshift-apiserver, pull requests merged in 2022-02, with the labels that each got.

#275 Bug 2047335: fix panic from printer
  pkg/project/printers/internalversion/printer_test.go
  pkg/security/printers/internalversion/printer.go
  pkg/security/printers/internalversion/printer_test.go
  pkg/template/printers/internalversion/printer.go
  pkg/template/printers/internalversion/printer_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#279 Bug 2049234: Fix importing images that have dots in their namespace
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#277 Bug 2043807: add deprecated parser build flag
  images/Dockerfile.rhel
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#281 Bug 2053218: Fix importing images that have dots in their namespace
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, staff-eng-approved, qe-approved, backport-risk-assessed

#283 Bug 2053223: Fix importing images that have dots in their namespace
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved, backport-risk-assessed

#282 Bug 2053222: Fix importing images that have dots in their namespace
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/crypto/missing_san.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client.go
  vendor/github.com/openshift/library-go/pkg/image/registryclient/client_mirrored.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved, backport-risk-assessed

#286 Bug 2041133: Bump openshift/api to 271bd7e1834c62853f1646b1bcb29aa4ec79d7c1
  go.mod
  go.sum
  hack/openapi-violation.list
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/register.go
  vendor/github.com/openshift/api/helm/v1beta1/types_helm.go
  vendor/github.com/openshift/api/helm/v1beta1/types_helm_chart_repository.go
  vendor/github.com/openshift/api/helm/v1beta1/types_project_helm_chart_repository.go
  vendor/github.com/openshift/api/helm/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machine.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/0000_10_machineset.crd.yaml
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_machine.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low, qe-approved
