Repository openshift/openshift-apiserver, pull requests merged in 2023-09, with the labels that each got.

#388 OCPBUGS-5823: remove unused service-ca roles
  pkg/bootstrappolicy/controller_policy.go
  pkg/bootstrappolicy/dead.go
  test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
  test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#387 OCPBUGS-17674: pkg/image: avoid unnecessary service lookups when registry is removed
  pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
  pkg/image/apiserver/registry/imagestream/etcd/etcd_test.go
  pkg/image/apiserver/registry/imagestream/strategy_test.go
  pkg/image/apiserver/registry/imagestreamimage/rest_test.go
  pkg/image/apiserver/registry/imagestreammapping/rest_test.go
  pkg/image/apiserver/registry/imagestreamtag/rest_test.go
  pkg/image/apiserver/registry/imagetag/rest_test.go
  pkg/image/apiserver/registryhostname/environmentresolvercache.go
  pkg/image/apiserver/registryhostname/environmentresolvercache_test.go
  pkg/image/apiserver/registryhostname/retriever.go
Labels: lgtm, approved

#386 OCPBUGS-16514: use import mode to manifest cache key
  pkg/image/apiserver/importer/importer.go
  pkg/image/apiserver/importer/importer_manifestlist_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
