Repository openshift/openshift-apiserver, pull requests merged in 2024-09, with the labels that each got.

#447 NO-JIRA: UPSTREAM: <carry>: retrying etcd Unavailable errors for the etcd health and ready checkers
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#448 OCPBUGS-35036: fail image import when both image and error are nil
  pkg/image/apiserver/importer/importer.go
  pkg/image/apiserver/importer/importer_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#449 OCPBUGS-42215: bump containers/image to v5.24.3
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference
