Repository openshift/openshift-apiserver, pull requests merged in 2025-02, with the labels that each got.

#495 OCPBUGS-49844: Prevent storage layer retries for methods with side effects.
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#496 OCPBUGS-49848: Prevent storage layer retries for methods with side effects.
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/storage/etcd3/etcd3retry/retry_etcdclient.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/retry_etcdprobemonitor.go
  vendor/modules.txt
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#475 OCPBUGS-44432: Skip blocked registry check for registries with mirrors
  pkg/image/apiserver/importer/importer.go
  pkg/image/apiserver/importer/importer_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference
